### ISSUE TITLE
urllib2.HTTPError: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.

### ISSUE THREAD

**Issue by thomasmerz** [HenrikBengtsson/speedtest-cli-extras#9]
Hi there,

since yesterday I got the following error when executing speedtest-csv:

Cron <root@merz-netbook> /usr/local/bin/speedtest-cli/speedtest-csv.sh --standardize --sep '\t' >> /usr/local/bin/speedtest-cli/results-`date +%Y-%m`.csv
09:50
(Cron Daemon)
An  root@merz-netbook
Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli/speedtest-cli.py", line 674, in <module>
    main()
  File "/usr/local/bin/speedtest-cli/speedtest-cli.py", line 668, in main
    speedtest()
  File "/usr/local/bin/speedtest-cli/speedtest-cli.py", line 518, in speedtest
    servers = closestServers(config['client'])
  File "/usr/local/bin/speedtest-cli/speedtest-cli.py", line 336, in closestServers
    uh = urlopen('http://www.speedtest.net/speedtest-servers.php')
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 646, in http_error_302
    self.inf_msg + msg, headers, fp)
urllib2.HTTPError: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found

speedtest-cli.py works fine:

Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Unitymedia (xxx)...
Selecting best server based on latency...
Hosted by xxx (xxx) [3.46 km]: 20.014 ms Testing download speed........................................
Download: 91.74 Mbit/s
Testing upload speed..................................................
Upload: 4.81 Mbit/s

Kind regards
Thomas

**Comment by HenrikBengtsson** [comment]
This looks like a hiccup with the Speedtest server you're happen to get and hopefully they'll fix it.

FYI, speedtest-csv uses speedtest-cli (https://github.com/sivel/speedtest-cli) for collecting the data.  If there's anything that could be done on the client side, then it would be an update to the latter.  So, if this doesn't resolve itself, please post an issue over there instead.

**Comment by HenrikBengtsson** [comment]
Forgot to clarify, basically, if you run
```sh
speedtest-cli
```
you'll see the same error (as `speedtest-csv`).
